<a href="https://colab.research.google.com/github/fael83/Smt4-Data-Mining/blob/main/Week16_Latihan3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

In [2]:
from google.colab import files
uploaded = files.upload()

Saving phishing_email_detection_2026_dataset.csv to phishing_email_detection_2026_dataset.csv

In [3]:
df = pd.read_csv("phishing_email_detection_2026_dataset.csv")
df.head()

,email_id,sender_email,subject,has_link,has_attachment,urgency_score,spelling_errors,email_length_words,is_phishing
0,1,harrisonsandra@paypal-alert.com,Meeting Reminder,0,1,2,0,227,0
1,2,randyharris@bankverify.net,Urgent Account Verification,1,1,9,7,59,1
2,3,adam13@outlook.com,Suspicious Login Attempt,1,1,8,10,67,1
3,4,kennethfisher@company-secure.com,Suspicious Login Attempt,0,1,9,8,102,1
4,5,wsandoval@paypal-alert.com,Your Password Will Expire,1,0,7,4,96,1

In [4]:
encoder = LabelEncoder()

for col in df.columns:

    if df[col].dtype == 'object':

        df[col] = encoder.fit_transform(df[col])

df.head()

,email_id,sender_email,subject,has_link,has_attachment,urgency_score,spelling_errors,email_length_words,is_phishing
0,1,465,4,0,1,2,0,227,0
1,2,1093,7,1,1,9,7,59,1
2,3,5,6,1,1,8,10,67,1
3,4,714,6,0,1,9,8,102,1
4,5,1448,9,1,0,7,4,96,1

In [6]:
X = df.drop("is_phishing", axis=1)
y = df["is_phishing"]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [8]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [9]:
hidden_layers = [
    (10,10,6),
    (6,8,9),
    (6,9,1),
    (6,3,9),
    (7,10,8)
]

hasil_hidden = []

for hl in hidden_layers:

    model = MLPClassifier(
        hidden_layer_sizes=hl,
        activation='relu',
        solver='adam',
        max_iter=1000,
        random_state=42
    )

    model.fit(X_train, y_train)

    pred = model.predict(X_test)

    acc = accuracy_score(y_test, pred)

    hasil_hidden.append(
        [str(hl), acc]
    )

hasil_hidden_df = pd.DataFrame(
    hasil_hidden,
    columns=[
        "Hidden Layer Size",
        "Accuracy"
    ]
)

hasil_hidden_df

  Hidden Layer Size  Accuracy
0       (10, 10, 6)       1.0
1         (6, 8, 9)       1.0
2         (6, 9, 1)       1.0
3         (6, 3, 9)       1.0
4        (7, 10, 8)       1.0

In [10]:
hidden_terbaik = hasil_hidden_df.loc[
    hasil_hidden_df["Accuracy"].idxmax()
]

print(hidden_terbaik)

Hidden Layer Size    (10, 10, 6)
Accuracy                     1.0
Name: 0, dtype: object

In [11]:
activations = [
    "identity",
    "logistic",
    "tanh",
    "relu"
]

hasil_activation = []

for act in activations:

    model = MLPClassifier(
        hidden_layer_sizes=(10,10,6),
        activation=act,
        solver='adam',
        max_iter=1000,
        random_state=42
    )

    model.fit(X_train, y_train)

    pred = model.predict(X_test)

    acc = accuracy_score(y_test, pred)

    hasil_activation.append(
        [act, acc]
    )

hasil_activation_df = pd.DataFrame(
    hasil_activation,
    columns=[
        "Activation",
        "Accuracy"
    ]
)

hasil_activation_df

  Activation  Accuracy
0   identity       1.0
1   logistic       1.0
2       tanh       1.0
3       relu       1.0

In [12]:
activation_terbaik = hasil_activation_df.loc[
    hasil_activation_df["Accuracy"].idxmax()
]

print(activation_terbaik)

Activation    identity
Accuracy           1.0
Name: 0, dtype: object

In [13]:
print("=== Hidden Layer Terbaik ===")
print(hidden_terbaik)

print()

print("=== Activation Terbaik ===")
print(activation_terbaik)

=== Hidden Layer Terbaik ===
Hidden Layer Size    (10, 10, 6)
Accuracy                     1.0
Name: 0, dtype: object

=== Activation Terbaik ===
Activation    identity
Accuracy           1.0
Name: 0, dtype: object

In [14]:
model_terbaik = MLPClassifier(
    hidden_layer_sizes=eval(hidden_terbaik["Hidden Layer Size"]),
    activation=activation_terbaik["Activation"],
    solver='adam',
    max_iter=1000,
    random_state=42
)

model_terbaik.fit(X_train, y_train)

pred = model_terbaik.predict(X_test)

accuracy = accuracy_score(y_test, pred)

print("Accuracy Terbaik :", accuracy)

Accuracy Terbaik : 1.0